-- Classic gathering nodes. `required` is the skill at which the node turns orange
-- and can be harvested. Below that, the client shows the name in red.
-- Difficulty bands after that match the client: orange +0, yellow +25, green +50, gray +100.
-- Names are the enUS object names shown on the minimap tooltip.

NopeNode_Nodes = {
	-- Herbalism
	["Peacebloom"] = { kind = "herb", required = 1 },
	["Silverleaf"] = { kind = "herb", required = 1 },
	["Earthroot"] = { kind = "herb", required = 15 },
	["Mageroyal"] = { kind = "herb", required = 50 },
	["Briarthorn"] = { kind = "herb", required = 70 },
	["Stranglekelp"] = { kind = "herb", required = 85 },
	["Bruiseweed"] = { kind = "herb", required = 100 },
	["Wild Steelbloom"] = { kind = "herb", required = 115 },
	["Grave Moss"] = { kind = "herb", required = 120 },
	["Kingsblood"] = { kind = "herb", required = 125 },
	["Liferoot"] = { kind = "herb", required = 150 },
	["Fadeleaf"] = { kind = "herb", required = 160 },
	["Goldthorn"] = { kind = "herb", required = 170 },
	["Khadgar's Whisker"] = { kind = "herb", required = 185 },
	["Wintersbite"] = { kind = "herb", required = 195 },
	["Firebloom"] = { kind = "herb", required = 205 },
	["Purple Lotus"] = { kind = "herb", required = 210 },
	["Wildvine"] = { kind = "herb", required = 210 },
	["Bloodvine"] = { kind = "herb", required = 210 },
	["Arthas' Tears"] = { kind = "herb", required = 220 },
	["Sungrass"] = { kind = "herb", required = 230 },
	["Blindweed"] = { kind = "herb", required = 235 },
	["Ghost Mushroom"] = { kind = "herb", required = 245 },
	["Gromsblood"] = { kind = "herb", required = 250 },
	["Golden Sansam"] = { kind = "herb", required = 260 },
	["Dreamfoil"] = { kind = "herb", required = 270 },
	["Mountain Silversage"] = { kind = "herb", required = 280 },
	["Plaguebloom"] = { kind = "herb", required = 285 },
	["Icecap"] = { kind = "herb", required = 290 },
	["Black Lotus"] = { kind = "herb", required = 300 },

	-- Mining
	["Copper Vein"] = { kind = "mine", required = 1 },
	["Tin Vein"] = { kind = "mine", required = 65 },
	["Incendicite Mineral Vein"] = { kind = "mine", required = 65 },
	["Silver Vein"] = { kind = "mine", required = 75 },
	["Ooze Covered Silver Vein"] = { kind = "mine", required = 75 },
	["Lesser Bloodstone Deposit"] = { kind = "mine", required = 75 },
	["Iron Deposit"] = { kind = "mine", required = 125 },
	["Indurium Mineral Vein"] = { kind = "mine", required = 150 },
	["Gold Vein"] = { kind = "mine", required = 155 },
	["Ooze Covered Gold Vein"] = { kind = "mine", required = 155 },
	["Mithril Deposit"] = { kind = "mine", required = 175 },
	["Ooze Covered Mithril Deposit"] = { kind = "mine", required = 175 },
	["Dark Iron Deposit"] = { kind = "mine", required = 230 },
	["Truesilver Deposit"] = { kind = "mine", required = 230 },
	["Ooze Covered Truesilver Deposit"] = { kind = "mine", required = 230 },
	["Small Thorium Vein"] = { kind = "mine", required = 245 },
	["Ooze Covered Thorium Vein"] = { kind = "mine", required = 245 },
	["Hakkari Thorium Vein"] = { kind = "mine", required = 245 },
	["Rich Thorium Vein"] = { kind = "mine", required = 275 },
	["Ooze Covered Rich Thorium Vein"] = { kind = "mine", required = 275 },
	["Small Obsidian Chunk"] = { kind = "mine", required = 305 },
	["Large Obsidian Chunk"] = { kind = "mine", required = 305 },
}
